sudo: required
dist: trusty
language: cpp

matrix:
  include:
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-4.9
#      env: MYCC=gcc-4.9 MYCXX=g++-4.9
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-5
#      env: MYCC=gcc-5 MYCXX=g++-5
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-6
#      env: MYCC=gcc-6 MYCXX=g++-6
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty
#          packages:
#            - clang-3.8
#      env: MYCC=clang-3.8 MYCXX=clang++-3.8
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-3.9
#          packages:
#            - clang-3.9
#      env: MYCC=clang-3.9 MYCXX=clang++-3.9
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-4.0
#          packages:
#            - clang-4.0
#      env: MYCC=clang-4.0 MYCXX=clang++-4.0
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
#          packages:
#            - mingw
      env: MYCC=x86_64-w64-mingw32-gcc MYCXX=x86_64-w64-mingw32-g++
    - os: linux
      env:
        - TEST="Clang Format"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-format
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make format
        - |
          if [[ -n $(git diff) ]]; then
            echo "You must run make format before submitting a pull request"
            echo ""
            git diff
            exit -1
          fi
    - os: linux
      env:
        - TEST="Clang Tidy"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-tidy-4.0
            - clang-4.0
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0
        - make tidy >output.txt
        - |
          if [[ -n $(grep "warning: " output.txt) ]] || [[ -n $(grep "error: " output.txt) ]]; then
              echo "You must pass the clang tidy checks before submitting a pull request"
              echo ""
              grep --color -E '^|warning: |error: ' output.txt
              exit -1;
          else
              echo -e "\033[1;32m\xE2\x9C\x93 passed:\033[0m $1";
          fi

before_install:
  - sudo apt-get install -y libgtest-dev
  - apt-cache search mingw

before_script:
  - cd /usr/src/gtest
  - if [[ "$MYCC" == *mingw* ]] ; then ADD_OPTS="-DCMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/Toolchain-cross-mingw-linux.cmake -Dgtest_disable_pthreads=ON"; fi
  - sudo cmake -DCMAKE_C_COMPILER=$MYCC -DCMAKE_CXX_COMPILER=$MYCXX $ADD_OPTS .
  - sudo cmake --build .
  - sudo mv libg* /usr/local/lib/
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir build
  - cd build
  - if [[ "$MYCC" == *mingw* ]] ; then ADD_OPTS="-DCMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/Toolchain-cross-mingw-linux.cmake"; fi
  - cmake -DCMAKE_C_COMPILER=$MYCC -DCMAKE_CXX_COMPILER=$MYCXX ..
  - make
  - make runtest

