dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libgtest-dev
      env: MYCC=gcc-4.9 MYCXX=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libgtest-dev
      env: MYCC=gcc-5 MYCXX=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libgtest-dev
      env: MYCC=gcc-6 MYCXX=g++-6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libgtest-dev
            - lcov
      env: MYCC=gcc-6 MYCXX=g++-6 CODE_COVERAGE=on
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-3.8
            - libgtest-dev
      env: MYCC=clang-3.8 MYCXX=clang++-3.8
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libgtest-dev
      env: MYCC=clang-3.9 MYCXX=clang++-3.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libgtest-dev
      env: MYCC=clang-4.0 MYCXX=clang++-4.0
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libgtest-dev
      env: MYCC=clang-5.0 MYCXX=clang++-5.0
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libgtest-dev
      env: MYCC=clang-5.0 MYCXX=clang++-5.0 ENABLE_ASAN=on
      # workaround for missing PTRACE capability, see https://github.com/travis-ci/travis-ci/issues/8836
      sudo: required
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libgtest-dev
      env: MYCC=clang-5.0 MYCXX=clang++-5.0 ENABLE_UBSAN=on
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-mingw-w64-x86-64
            - libgtest-dev
      env: MYCC=/usr/bin/x86_64-w64-mingw32-gcc MYCXX=/usr/bin/x86_64-w64-mingw32-g++
    - os: linux
      env:
        - TEST="Clang Format"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-format-4.0
            - clang-4.0
            - libgtest-dev
      script:
        - mkdir build
        - cd build
        - ADD_OPTS="-DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0"
        - ADD_OPTS="$ADD_OPTS -DGTEST_LIBRARY=$TRAVIS_BUILD_DIR/gtest/libgtest.a"
        - ADD_OPTS="$ADD_OPTS -DGTEST_MAIN_LIBRARY=$TRAVIS_BUILD_DIR/gtest/libgtest_main.a"
        - ADD_OPTS="$ADD_OPTS -DGTEST_INCLUDE_DIR=$TRAVIS_BUILD_DIR/gtest"
        - ADD_OPTS="$ADD_OPTS -DCLANG_FORMAT=/usr/bin/clang-format-4.0"
        - cmake $ADD_OPTS ..
        - make format
        - |
          if [[ -n $(git diff) ]]; then
            echo "You must run make format before submitting a pull request"
            echo ""
            git diff
            exit -1
          fi
    - os: linux
      env:
        - TEST="Clang Tidy"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-tidy-4.0
            - clang-4.0
            - libgtest-dev
      script:
        - mkdir build
        - cd build
        - ADD_OPTS="-DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0"
        - ADD_OPTS="$ADD_OPTS -DGTEST_LIBRARY=$TRAVIS_BUILD_DIR/gtest/libgtest.a"
        - ADD_OPTS="$ADD_OPTS -DGTEST_MAIN_LIBRARY=$TRAVIS_BUILD_DIR/gtest/libgtest_main.a"
        - ADD_OPTS="$ADD_OPTS -DGTEST_INCLUDE_DIR=$TRAVIS_BUILD_DIR/gtest"
        - cmake $ADD_OPTS ..
        - make tidy >output.txt
        - |
          if [[ -n $(grep "warning: " output.txt) ]] || [[ -n $(grep "error: " output.txt) ]]; then
              echo "You must pass the clang tidy checks before submitting a pull request"
              echo ""
              grep --color -E '^|warning: |error: ' output.txt
              exit -1;
          else
              echo -e "\033[1;32m\xE2\x9C\x93 passed:\033[0m $1";
          fi

before_script:
  - mkdir gtest
  - pushd gtest
  - ln -s /usr/include/gtest .
  - ln -s /usr/src/gtest/src .
  - ln -s /usr/src/gtest/CMakeLists.txt .
  - ln -s /usr/src/gtest/cmake .
  - |
    if [[ "$MYCC" == *mingw* ]] ; then
      ADD_OPTS="-DCMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/Toolchain-cross-mingw-linux.cmake -Dgtest_disable_pthreads=ON"
    else
      ADD_OPTS="-DCMAKE_C_COMPILER=$MYCC -DCMAKE_CXX_COMPILER=$MYCXX"
    fi
  - cmake $ADD_OPTS .
  - cmake --build .
  - popd

script:
  - mkdir build
  - cd build
  - BUILD_TYPE=Release
  - |
    if [[ "$MYCC" == *mingw* ]] ; then
      ADD_OPTS="-DCMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/Toolchain-cross-mingw-linux.cmake"
    else
      ADD_OPTS="-DCMAKE_C_COMPILER=$MYCC -DCMAKE_CXX_COMPILER=$MYCXX"
    fi
  - ADD_OPTS="$ADD_OPTS -DGTEST_LIBRARY=$TRAVIS_BUILD_DIR/gtest/libgtest.a"
  - ADD_OPTS="$ADD_OPTS -DGTEST_MAIN_LIBRARY=$TRAVIS_BUILD_DIR/gtest/libgtest_main.a"
  - ADD_OPTS="$ADD_OPTS -DGTEST_INCLUDE_DIR=$TRAVIS_BUILD_DIR/gtest"
  - |
    if [[ -n "$ENABLE_ASAN" ]] ; then
      ADD_OPTS="$ADD_OPTS -DENABLE_ASAN=$ENABLE_ASAN"
      BUILD_TYPE=Debug
    fi
  - |
    if [[ -n "$ENABLE_UBSAN" ]] ; then
      ADD_OPTS="$ADD_OPTS -DENABLE_UBSAN=$ENABLE_UBSAN"
      BUILD_TYPE=Debug
    fi
  - |
    if [[ -n "$CODE_COVERAGE" ]] ; then
      ADD_OPTS="$ADD_OPTS -DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage'"
      BUILD_TYPE=Debug
    fi
  - ADD_OPTS="$ADD_OPTS -DCMAKE_BUILD_TYPE=$BUILD_TYPE"
  - cmake $ADD_OPTS ..
  - make
  - if [[ "$MYCC" != *mingw* ]] ; then make runtest; fi
  - |
    if [[ -n "$CODE_COVERAGE" ]] ; then
      lcov -d . -c -o coverage.info                      # parse coverage data
      lcov -r coverage.info "/usr*" -o coverage.info     # remove data for system headers
      lcov -l coverage.info                              # just list a short summary of the results
      bash <(curl -s https://codecov.io/bash)
    fi
