# Windows Build Configuration for AppVeyor

image:
- Visual Studio 2019


build_script:
  - git submodule update --init --recursive
  - set buildcfg=Release
  - md build
  - cd build
  - cmake .. -A x64
  - cmake --build . --config %buildcfg%

test_script:
  - ctest -VV
