# Windows Build Configuration for AppVeyor

image:
- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017


build_script:
  - set buildcfg=Release
  - md build
  - cd build
  - cmake ..
  - cmake --build . --config %buildcfg%

test_script:
  - ctest -VV
